# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wats.io
email: watsonboyett@gmail.com
description: Some projects I've worked on.
url: "http://watsonboyett.github.io" # the base hostname & protocol for your site
github_username:  watsonboyett

# Build settings
markdown: kramdown
